### PR TITLE
Added hacs.json for use with HACS UI

### PR DESCRIPTION
**Pull request by jrhubott**

### CODE REVIEW

**Comment by PeteRager** [comment]
Thanks for this update!  Does this just work with HA, do I need to update the readme?

**Comment by deviantintegral** [comment]
Can someone provide testing instructions? I just added this integration as a custom HACS addon, and it worked fine, but as this is new to my install I can easily remove it provide a screencap of what this does.

**Comment by PeteRager** [comment]
Right now I don’t have a HACS environment setup to test or document this enhancement.  Since it worked for you, that covers the testing.   What would be helpful would be the content / screen caps of how to install via HACS that we can add to the readme.

**Comment by deviantintegral** [comment]
What I was trying to say is that I don't know of a way to point an HACS repository to a specific branch, so currently this file isn't being picked up. I'm not seeing any mention of "branch" in the HACS docs, so perhaps it's a "merge and hope" type of testing.

Screen Shot 2021-09-08 at 5 31 11 PM

**Comment by PeteRager** [comment]
Got it.   I merged it to master,  I think I got the newline added.  Maybe it’ll work now?

**Pull request merged**
